spring.application.name=mon-salon

# Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/mon_salon_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1/mon-salon
#server.port=8090


# Configuration JWT & Sécurité
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 24 heures en millisecondes (24 * 60 * 60 * 1000)
app.jwt.expiration-ms=86400000
# 7 jours en millisecondes (7 * 24 * 60 * 60 * 1000)
app.jwt.refresh-expiration-ms=604800000
app.jwt.cookie-name=refreshToken
# true en HTTPS (production), false en HTTP (développement local)
app.jwt.cookie-secure=false


cloudinary.cloud_name=dfik1cvmn
cloudinary.api_key=629565588293995
cloudinary.api_secret=oFkvv2jkPi3D86ov06hT-k2ekiQ

# Configuration Multipart (Téléversement de vidéos réalisations & stories jusqu'à 100 Mo)
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Configuration Assistant Virtuel Gemini
gemini.api-key=AQ.Ab8RN6I20eVQRr9JkHWqvN5K833rsxSoYvwx68yj3qfi_PmfFA
gemini.model=gemini-3.8-flash
gemini.base-url=https://generativelanguage.googleapis.com/v1beta
gemini.timeout-ms=15000

